services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: sample-app
    ports:
      - 5432:5432
    volumes:
      - ./dbscripts:/docker-entrypoint-initdb.d
      - ./postgres-data:/var/lib/postgresql/data
  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
  backend-go:
    build:
      context: ./backend-go
    depends_on:
      - postgres
      - redis
    volumes:
      - ./backend-go:/go-server
    ports:
      - 3000:3000
    environment:
      - DB_STR=postgres://root:root@postgres/sample-app?sslmode=disable
      - JWT_SECRET=my-secret-123
      - REDIS_ADDR=redis:6379
      - NR_LICENSE=your-newrelic-license
  backend-ts:
    build:
      context: ./backend-typescript
    depends_on:
      - postgres
    volumes:
      - ./backend-typescript/src:/ts-server/src
    ports:
      - 3000:3000
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=sample-app
      - JWT_SECRET=my-secret-123