services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: sample-app
    ports:
      - 5432:5432
    volumes:
      - ./dbscripts:/docker-entrypoint-initdb.d
      - ./postgres-data:/var/lib/postgresql/data
  backend-go:
    build:
      context: ./backend-go
    depends_on:
      - postgres
    volumes:
      - ./backend-go:/go-server
    ports:
      - 3000:3000
    environment:
      - DB_STR=postgres://root:root@postgres/sample-app?sslmode=disable
      - JWT_SECRET=my-secret-123