name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'
        working-directory: ./backend-go

    - name: Fetch dependencies
      working-directory: ./backend-go
      run: go get .

    - name: Test
      working-directory: ./backend-go
      run: go test -v ./...

    - name: Build
      working-directory: ./backend-go
      run: go build

    - name: Create Release
      uses: softprops/action-gh-release@v2