name: PR Check

on:
  pull_request:
    branches: [ "main" ]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend-go
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'
      
    - name: Fetch dependencies
      run: go get .

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...